-- [표현법] CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C##SERVER IDENTIFIED BY SERVER;

-- [표현법] GRANT 권한1, 권한2, ... TO 계정명;
GRANT CONNECT, RESOURCE TO "C##SERVER";

-- 테이블 스페이스 관련 설정
ALTER USER "C##SERVER" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;